
all:
	@mkdir -p dist
	@g++ -std=c++17 -g src/avm_main.cpp public/helper.hpp public/Instruction.hpp public/Memory_Cell.hpp public/AVM.hpp public/arithmetic_exec.hpp public/funcs_exec.hpp public/jumps_exec.hpp public/libfuncs_Impl.hpp public/tables_exec.hpp   -o dist/avm
